# Generated by Django 3.2.6 on 2021-08-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=255)),
                ('ipaddress', models.CharField(max_length=255)),
                ('port', models.IntegerField(max_length=4)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
