# Generated by Django 4.1.9 on 2023-07-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exam_slot',
            fields=[
                ('exam_slot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('exam_slot_starttime', models.DateTimeField()),
                ('exam_slot_endtime', models.DateTimeField()),
                ('exam_slot_code', models.CharField(max_length=255)),
                ('exam_slot_name', models.CharField(max_length=255)),
                ('record_tracking', models.TimeField()),
                ('exam_slotreportingtime', models.CharField(max_length=255)),
                ('exam_slot_status', models.BooleanField()),
                ('exam_date', models.TimeField()),
                ('exam_schedule_id', models.IntegerField()),
                ('exam_slot_shift', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'exam_slot',
                'managed': 'postgresql',
            },
        ),
    ]
