# Generated by Django 4.1.9 on 2023-07-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navyjuly', '0002_remove_exam_slot_exam_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_slot',
            name='exam_slot_id',
        ),
        migrations.AddField(
            model_name='exam_slot',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
